SET SERVEROUTPUT ON;
CREATE OR REPLACE PACKAGE DISPLAY AS PROCEDURE SHOW_FIRST_NAME;
END DISPLAY;
/
CREATE OR REPLACE PACKAGE BODY DISPLAY AS
PROCEDURE SHOW_FIRST_NAME IS
FIRSTNAME VARCHAR2(50);
    BEGIN
        SELECT FIRST_NAME INTO FIRSTNAME FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=100;
        DBMS_OUTPUT.PUT_LINE(FIRSTNAME);
    END SHOW_FIRST_NAME;
END DISPLAY;
/
EXECUTE DISPLAY.SHOW_FIRST_NAME;
