SET SERVEROUTPUT ON;

CREATE OR REPLACE PACKAGE STAJ_UTILITY AS
PROCEDURE PRINT_DAY;
FUNCTION GET_DAY RETURN VARCHAR2;
END STAJ_UTILITY;


CREATE OR REPLACE PACKAGE BODY STAJ_UTILITY IS
PROCEDURE PRINT_DAY IS
BEGIN
    DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE, 'Day'));
END PRINT_DAY;

FUNCTION GET_DAY RETURN VARCHAR2 AS
BEGIN
    RETURN TO_CHAR(SYSDATE, 'Day');
END GET_DAY;

END STAJ_UTILITY;
/

EXECUTE STAJ_UTILITY.PRINT_DAY;