SET SERVEROUTPUT ON;

CREATE OR REPLACE DIRECTORY BACK_UP AS 'C:\app\7378\product\18.0.0\work';


GRANT READ,WRITE,EXECUTE ON DIRECTORY BACK_UP TO PUBLIC;

CREATE OR REPLACE PACKAGE UTILITY_EMPLOYEES_PACKAGE AS PROCEDURE EMPLOYEES;
END UTILITY_EMPLOYEES_PACKAGE;



CREATE OR REPLACE PACKAGE BODY UTILITY_EMPLOYEES_PACKAGE  AS
PROCEDURE EMPLOYEES IS
CURSOR C_EMPLOYEES IS (SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.LAST_NAME, EMP.SALARY, DEP.DEPARTMENT_NAME 
                       FROM EMPLOYEES EMP INNER JOIN DEPARTMENTS DEP 
                       ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID);
SAVING UTL_FILE.FILE_TYPE;
COUNTER NUMBER :=0;
    BEGIN
        SAVING := UTL_FILE.FOPEN('BACK_UP', 'INFOS.txt' , 'W');
        FOR WORKER IN C_EMPLOYEES LOOP
            COUNTER:= COUNTER+1 ;
            UTL_FILE.PUT_LINE(SAVING , 'Id--> ' || WORKER.EMPLOYEE_ID 
                                                    || ' Name--> ' || WORKER.FIRST_NAME 
                                                    || ' Surname--> ' || WORKER.LAST_NAME 
                                                    || ' Salary--> ' || WORKER.SALARY 
                                                    || ' Department--> ' || WORKER.DEPARTMENT_NAME);
        END LOOP;
        UTL_FILE.PUT_LINE(SAVING , 'Total Records--> ' || COUNTER );
        UTL_FILE.FCLOSE(SAVING);

    END EMPLOYEES;
END UTILITY_EMPLOYEES_PACKAGE;


/
EXECUTE UTILITY_EMPLOYEES_PACKAGE.EMPLOYEES;






