
--PLSQL01-EX-06;

SELECT JOB_ID DEPARTMENT_NAME , SUM(SALARY) TOTAL_SALARY FROM HR.EMPLOYEES GROUP BY JOB_ID;

SELECT DISTINCT JOB_ID DEPARTMENT_NAME , SUM(SALARY) OVER(PARTITION BY JOB_ID) TOTAL_SALARY FROM HR.EMPLOYEES;

---------------------------------------------------------------