SET SERVEROUTPUT ON;

CREATE OR REPLACE DIRECTORY BACK_UP AS 'C:\app\7378\product\18.0.0\work';
GRANT READ,WRITE,EXECUTE ON DIRECTORY BACK_UP TO PUBLIC;


CREATE OR REPLACE PROCEDURE INFO_RICHEST IS 
    SAVING   UTL_FILE.FILE_TYPE;
    BEGIN
        DECLARE
        RICHEST_FIRST_NAME    EMPLOYEES.FIRST_NAME%TYPE;
        RICHEST_LAST_NAME     EMPLOYEES.LAST_NAME%TYPE;
        RICHEST_SALARY        EMPLOYEES.SALARY%TYPE;
        BEGIN
            SELECT FIRST_NAME, LAST_NAME, SALARY 
            INTO RICHEST_FIRST_NAME, RICHEST_LAST_NAME, RICHEST_SALARY
            FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);
            
            SAVING := UTL_FILE.FOPEN('BACK_UP', 'INFOS.txt' , 'W');
            
            UTL_FILE.PUT_LINE(SAVING ,'First Name of the Richest Employee: '|| RICHEST_FIRST_NAME);
            UTL_FILE.PUT_LINE(SAVING ,'Last Name of the Richest Employee: '|| RICHEST_LAST_NAME);
            UTL_FILE.PUT_LINE(SAVING ,'Salary of the Richest Employee: ' || RICHEST_SALARY);
            UTL_FILE.FCLOSE(SAVING);
        END;
        
    END INFO_RICHEST;

/
EXECUTE INFO_RICHEST();