CREATE TABLE DEP AS (SELECT * FROM DEPARTMENTS);
CREATE TABLE EMP AS (SELECT * FROM EMPLOYEES);

--SQL03-EX-01:

ALTER TABLE EMP ADD (MAX_SALARY NUMBER(6));

UPDATE EMP SET MAX_SALARY = (SELECT MAX(SALARY) FROM EMP);

DELETE FROM EMP WHERE EMP.SALARY=(SELECT MIN(EMP.SALARY) FROM EMP);

---------------------------------------------------------------

--SQL03-EX-02:

CREATE INDEX DPR_NAME_IDX ON DEP (DEPARTMENT_NAME);

ALTER TABLE EMP ADD CONSTRAINT CNSTR_SALARY CHECK (SALARY>1000 AND SALARY<100000);

DROP INDEX DPR_NAME_IDX;

ALTER TABLE EMP ENABLE CONSTRAINT CNSTR_SALARY;
ALTER TABLE EMP DISABLE CONSTRAINT CNSTR_SALARY;
ALTER TABLE EMP DROP CONSTRAINT CNSTR_SALARY;

---------------------------------------------------------------

--SQL03-EX-03:

CREATE TABLE EMP_DEP AS (SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES);

ALTER TABLE EMP_DEP ADD (DEPARTMENT_NAME VARCHAR2(20));

MERGE INTO EMP_DEP x USING DEPARTMENTS y
ON (x.DEPARTMENT_NAME = y.DEPARTMENT_NAME)
WHEN MATCHED THEN UPDATE SET x.DEPARTMENT_ID = y.DEPARTMENT_ID
WHEN NOT MATCHED THEN
	INSERT (DEPARTMENT_ID,DEPARTMENT_NAME) VALUES (Y.DEPARTMENT_ID,y.DEPARTMENT_NAME);


--------------------------------------------------------------------------------------

--SQL03-EX-04:

WITH
EMP AS (
    SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES
    WHERE JOB_ID LIKE 'S%'),
JOB_TITLES AS (
    SELECT JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY FROM JOBS),
DEP_NAMES AS(
    SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS)
SELECT EMP.FIRST_NAME,
       EMP.LAST_NAME,
       EMP.JOB_ID,
       JOB_TITLES.JOB_TITLE,
       JOB_TITLES.MIN_SALARY,
       JOB_TITLES.MAX_SALARY,
       EMP.DEPARTMENT_ID,
       DEP_NAMES.DEPARTMENT_NAME
FROM EMP, DEP_NAMES, JOB_TITLES
WHERE EMP.DEPARTMENT_ID = DEP_NAMES.DEPARTMENT_ID AND EMP.JOB_ID = JOB_TITLES.JOB_ID;
--------------------------------------------------------------------------------------

--SQL03-EX-05:

--COMMIT komutu ile çalýþtýrýlan tüm SQL komutlarýnýn baþarýlý olmasý halinde iþlemler veri tabanýna yansýtýlýr.
--ROLLBACK komutu ise herhangi bir hata oluþumunda tüm iþlemleri geri alýr.
